param(
    [string]$AppName = "FilterPlus",
    [string]$Version = "1.1.0",
    [string]$Author = "DBDev_dbarberos",
    [string]$Email = "dbarberos@outlook.com",
    [string]$ProjectDir = "."
)

$ErrorActionPreference = "Stop"

# Paths
$BundleName = "$AppName.bundle"
$DeployDir = Join-Path $ProjectDir "Deploy"
$BundlePath = Join-Path $DeployDir $BundleName
$AssetsDir = Join-Path $ProjectDir "..\.agents\skills\revit-appstore-bundle\assets"

Write-Host "Building Autodesk App Store Bundle for $AppName v$Version..."

# Prepare Deploy and Archive directories
if (-not (Test-Path $DeployDir)) {
    New-Item -ItemType Directory -Path $DeployDir | Out-Null
}
$ArchiveDir = Join-Path $DeployDir "Archive"
if (-not (Test-Path $ArchiveDir)) {
    New-Item -ItemType Directory -Path $ArchiveDir | Out-Null
}

# Archive any older zip files found in Deploy
$OldZips = Get-ChildItem -Path $DeployDir -Filter "*.zip"
foreach ($zip in $OldZips) {
    # We move it to archive if it's not the one we are about to create
    Move-Item -Path $zip.FullName -Destination $ArchiveDir -Force
}

# Clean ONLY the temporary staging bundle folder, not the whole Deploy dir
if (Test-Path $BundlePath) {
    Remove-Item -Path $BundlePath -Recurse -Force
}
New-Item -ItemType Directory -Path $BundlePath | Out-Null

# Create basic Contents folder
$ContentsPath = Join-Path $BundlePath "Contents"
New-Item -ItemType Directory -Path $ContentsPath | Out-Null

# We will scan for compiled versions in bin/ (either Release or Debug, prefer Release)
$BinDir = Join-Path $ProjectDir "bin"
if (-not (Test-Path $BinDir)) {
    Write-Error "Bin directory not found. Please compile the project first."
}

# Find all version folders (e.g. Release.R24, Debug.R25)
$AllDirs = Get-ChildItem -Path $BinDir -Directory | Where-Object { $_.Name -match "\.R(\d{2})$" }
if ($AllDirs.Count -eq 0) {
    Write-Error "No compiled versions found in bin/. E.g. bin/Release.R24"
}

# Group by Year and select Release if available, else whatever is there
$VersionDirs = @()
$Groups = $AllDirs | Group-Object { $_.Name -replace ".*\.R(\d{2})$", "`$1" }
foreach ($g in $Groups) {
    $release = $g.Group | Where-Object { $_.Name -like "Release*" } | Select-Object -First 1
    if ($release) {
        $VersionDirs += $release
    } else {
        $VersionDirs += $g.Group[0]
    }
}

$ComponentsXml = ""

foreach ($vDir in $VersionDirs) {
    # Extract year (e.g. R24 -> 2024)
    $vDir.Name -match "R(\d{2})$" | Out-Null
    $Year = "20" + $matches[1]

    # Look for the publish folder generated by Nice3point
    $PublishDir = Join-Path $vDir.FullName "publish\$AppName"
    if (-not (Test-Path $PublishDir)) {
        Write-Warning "Publish folder not found for $Year ($PublishDir). Skipping."
        continue
    }

    Write-Host "Found version $Year, packing..."
    
    # Create Contents/202X folder
    $TargetVersionDir = Join-Path $ContentsPath $Year
    New-Item -ItemType Directory -Path $TargetVersionDir -Force | Out-Null
    
    # Copy all files from publish
    Copy-Item -Path "$PublishDir\*" -Destination $TargetVersionDir -Recurse -Force

    # Ensure help.html is included in the version's Resources folder for Contextual Help
    $TargetResourcesDir = Join-Path $TargetVersionDir "Resources"
    if (-not (Test-Path $TargetResourcesDir)) { New-Item -ItemType Directory -Path $TargetResourcesDir | Out-Null }
    $HelpSrc = Join-Path $ProjectDir "Resources\help.html"
    if (Test-Path $HelpSrc) {
        Copy-Item -Path $HelpSrc -Destination $TargetResourcesDir -Force
    }

    # If the addin is in the version folder, move it to the correct path or leave it?
    # Actually, Autodesk requires the addin file inside the bundle.
    # The xml should point to: ./Contents/2024/AppName.addin

    # Generate XML snippet
    $ComponentsXml += @"
  <Components Description="$AppName Add-in for Revit $Year">
    <RuntimeRequirements OS="Win64" Platform="Revit" SeriesMin="R$Year" SeriesMax="R$Year" />
    <ComponentEntry AppName="$AppName" Version="$Version" ModuleName="./Contents/$Year/$AppName.addin" AppDescription="Filter and Selection add-in" LoadOnRevitStartup="True" />
  </Components>
"@ + "`r`n"
}

# Also copy Resources/Icons if available so they can be referenced in XML
$IconsSrc = Join-Path $ProjectDir "Resources\Icons"
if (Test-Path $IconsSrc) {
    $IconsDest = Join-Path $ContentsPath "Resources\Icons"
    New-Item -ItemType Directory -Path $IconsDest -Force | Out-Null
    Copy-Item -Path "$IconsSrc\*" -Destination $IconsDest -Recurse -Force
}

# Also copy Docs if available (Only the user_guide, we don't want internal references)
$DocsSrc = Join-Path $ProjectDir "docs"
if (Test-Path $DocsSrc) {
    $DocsDest = Join-Path $BundlePath "docs"
    New-Item -ItemType Directory -Path $DocsDest -Force | Out-Null
    
    # Check if user_guide is in docs or docs/references
    $UserGuidePath = Join-Path $DocsSrc "references\user_guide.md"
    if (-not (Test-Path $UserGuidePath)) {
        $UserGuidePath = Join-Path $DocsSrc "user_guide.md"
    }

    if (Test-Path $UserGuidePath) {
        Copy-Item -Path $UserGuidePath -Destination $DocsDest -Force
    }
}

# Generate ProductCode (New GUID)
$ProductCode = [guid]::NewGuid().ToString().ToUpper()

# Process XML Template
$XmlTemplatePath = Join-Path $AssetsDir "PackageContents.xml"
if (-not (Test-Path $XmlTemplatePath)) {
    Write-Error "PackageContents.xml template not found at $XmlTemplatePath"
}

$XmlContent = Get-Content -Path $XmlTemplatePath -Raw
$XmlContent = $XmlContent -replace "\{\{Version\}\}", $Version
$XmlContent = $XmlContent -replace "\{\{AppName\}\}", $AppName
$XmlContent = $XmlContent -replace "\{\{Author\}\}", $Author
$XmlContent = $XmlContent -replace "\{\{Email\}\}", $Email
$XmlContent = $XmlContent -replace "\{\{ProductCode\}\}", $ProductCode
$XmlContent = $XmlContent -replace "\{\{Components\}\}", $ComponentsXml

$XmlTargetPath = Join-Path $BundlePath "PackageContents.xml"
[System.IO.File]::WriteAllText($XmlTargetPath, $XmlContent)

Write-Host "Bundle folder generated at: $BundlePath"

# Compress to ZIP
$ZipPath = Join-Path $DeployDir "$AppName`_v$Version.zip"
if (Test-Path $ZipPath) { Remove-Item $ZipPath -Force }

Write-Host "Waiting a moment to release file locks..."
Start-Sleep -Seconds 3

# Temporarily move PackageContents.xml out of the bundle so it's not in the ZIP (Autodesk Store rule)
$XmlTempPath = Join-Path $DeployDir "PackageContents.xml"
if (Test-Path $XmlTargetPath) {
    Move-Item -Path $XmlTargetPath -Destination $XmlTempPath -Force
}

Write-Host "Zipping bundle (without PackageContents.xml for App Store)..."
Add-Type -AssemblyName System.IO.Compression.FileSystem
[System.IO.Compression.ZipFile]::CreateFromDirectory($BundlePath, $ZipPath)

# Move PackageContents.xml back so local testing still works
if (Test-Path $XmlTempPath) {
    Move-Item -Path $XmlTempPath -Destination $XmlTargetPath -Force
}

Write-Host "Bundle ZIP created at: $ZipPath"
Write-Host "Done!"
